use std::time::Duration;

use elliptic_curve::pkcs8::DecodePublicKey;

use tlsn_core::proof::{SessionProof, TlsProof};

use std::io::Cursor;
use byteorder::{BigEndian, ReadBytesExt};

/// A simple verifier which reads a proof generated by `simple_prover.rs` from "proof.json", verifies
/// it and prints the verified data to the console.
fn main() {
    // Deserialize the proof
    let proof = std::fs::read_to_string("proof.json").unwrap();
    let proof: TlsProof = serde_json::from_str(proof.as_str()).unwrap();
    let notary_pubkey = notary_pubkey();

    // let mut rdr = Cursor::new(proof);

    println!("Proof {:?}", proof);
    println!("Proof {:?}", notary_pubkey);
}

/// Returns a Notary pubkey trusted by this Verifier
fn notary_pubkey() -> p256::PublicKey {
    let pem_file_path = "../../notary-server/fixture/notary/notary.pub";

    p256::PublicKey::read_public_key_pem_file(pem_file_path).unwrap()
}
